### PR TITLE
(discard) Fix documentation favicon, avatar image and background pattern.

### PR DESCRIPTION
**Pull request by josue**
Fixes PR #49 

Preview:

### CODE REVIEW

**Comment by 3p3r** [comment]
@josue the gh-pages branch is what GH pages uses to deploy the documentation and it's not meant to be committed to directly. The documentation is generated by Docsify and automated by GH actions when you merge into master.

**Comment by josue** [comment]
@3p3r ahh, yikes!  😱 i missed that, thanks!

**Comment by 3p3r** [comment]
no worries, honestly the gh-pages branch needs to be reset from scratch. it contains so much unnecessary files. it's confusing. I'll make a ticket for myself to fix it soon.

**Comment by mneil** [comment]
I know this is closed but regarding the extra stuff in gh-pages the drone plugin force pushes everything - wiping out old files. I wouldn't be surprised if there was an option to do the same with the action I used. I'd start there.

**Pull request merged**
